spring:
  application:
    name: moneymanager

  datasource:
    url: jdbc:mysql://localhost:3306/moneymanager
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_USERNAME}
    password: ${BREVO_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          from: ${BREVO_FROM_EMAIL}

server:
  port: 5000